default:
  image: debian:latest

build:
  before_script:
    - apt-get -qq update
    - apt-get install -y build-essential
    - apt-get install -y git
    - apt-get install -y wget
    - apt-get install -y --no-install-recommends perl
    - apt-get install -y --no-install-recommends texlive texlive-latex-extra
    - apt-get install -y latexmk
    - apt-get install -y pandoc
    - apt-get install -y imagemagick
    - sed -i '/disable ghostscript format types/,+6d' /etc/ImageMagick-6/policy.xml
  script: make all
  artifacts:
    paths:
      - _build/**
